### ISSUE TITLE
no component clickable on dashboard after superadmin login

### ISSUE THREAD

**Issue by meghakundu** [MusheAbdulHakim/Laravel-Smarthr#43]
![image](https://github.com/user-attachments/assets/a2e32b9d-36da-40b8-83b1-80e7a6c6385e)
The dashboard is not clickable and same for other logins too for each user role. Please help with this @MusheAbdulHakim

**Comment by MusheAbdulHakim** [comment]
Make sure you run the seeders
```
php artisan module:seed
```

**Comment by rubelmia2091996** [comment]
<img width="959" alt="smarthr" src="https://github.com/user-attachments/assets/b0c88878-a58a-4d6d-a444-e7d5653bb61e">
same issue I follow the whole installation process and run all the commands. But still it's loading. could you please guide me @MusheAbdulHakim

**Comment by MusheAbdulHakim** [comment]
can you elaborate more on the issue?.
With @meghakundu , he couldn't see the components. Yours is loading so you should be able to access them.
Let me know the exact problem you are facing. Add code samples, screenshots and any other detail that might be helpful in solving the issue

**Comment by SafdarAlli** [comment]
This issue is not solved till yet

**Comment by itsAnkitpy** [comment]
One thing i noticed is that if I load jquery using cdn in partials/scripts.blade.php it resolves the loader error 
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.x.x/dist/js/bootstrap.bundle.min.js"></script>

The thing is I am still not able to click on Add Employee or any other modals of the system. I think it must be because of conflicting javascript. I shall update if I find any solution from my end.

**Comment by meghakundu** [comment]
Ok, thanks for the update.

**Comment by THnnNaing** [comment]
thanks for the update

**Comment by itsAnkitpy** [comment]
If anybody is just using php artisan serve, just note that we also have to run npm run dev in the second terminal.
